# Generated by Django 3.0.8 on 2020-08-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jasoseol',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
